In [1]:
import numpy

In [2]:
n = numpy.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [6]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
m = numpy.asarray([[123, 123, 12343, 1234, 3232], [], []])
m

array([list([123, 123, 12343, 1234, 3232]), list([]), list([])],
      dtype=object)

In [8]:
type(m)

numpy.ndarray

In [9]:
print(m)

[list([123, 123, 12343, 1234, 3232]) list([]) list([])]


In [1]:
import cv2

In [5]:
img = cv2.imread("smallgray.png", 0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
cv2.imwrite("newsmallgray.png", img)

True

In [8]:
img[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [10]:
img.shape

(3, 5)

In [11]:
img[2, 4]

182

In [16]:
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [18]:
import numpy

In [20]:
ims = numpy.hstack((img, img))

In [21]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [23]:
lst = numpy.hsplit(ims, 5)

In [24]:
lst

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8), array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8), array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8), array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8), array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]